//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace УПпрактика
{
    using System;
    using System.Collections.Generic;
    
    public partial class Matchup
    {
        public int MatchupId { get; set; }
        public Nullable<int> SeasonId { get; set; }
        public Nullable<int> MatchupTypeId { get; set; }
        public Nullable<int> Team_Away { get; set; }
        public Nullable<int> Team_Home { get; set; }
        public Nullable<System.DateTime> Starttime { get; set; }
        public Nullable<int> Team_Away_Score { get; set; }
        public int Team_Home_Score { get; set; }
        public string Location { get; set; }
        public Nullable<int> Status { get; set; }
        public string CurrentQuarter { get; set; }
    }
}
