//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace УПпрактика
{
    using System;
    using System.Collections.Generic;
    
    public partial class MatchupLog
    {
        public Nullable<int> Id { get; set; }
        public Nullable<int> MatchupId { get; set; }
        public Nullable<int> Quarter { get; set; }
        public string OccurTime { get; set; }
        public Nullable<int> TeamId { get; set; }
        public Nullable<int> PlayerId { get; set; }
        public Nullable<int> ActionTypeId { get; set; }
        public string Remark { get; set; }
    }
}
