//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace УПпрактика
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlayerStatistics
    {
        public int Id { get; set; }
        public Nullable<int> MatchupId { get; set; }
        public Nullable<int> TeamId { get; set; }
        public Nullable<int> PlayerId { get; set; }
        public Nullable<int> IsStarting { get; set; }
        public Nullable<decimal> Min { get; set; }
        public Nullable<int> Point { get; set; }
        public Nullable<int> Assist { get; set; }
        public Nullable<int> FieldGoalMade { get; set; }
        public Nullable<int> FieldGoalMissed { get; set; }
        public Nullable<int> C_3_PointFieldGoalMade { get; set; }
        public Nullable<int> C_3_PointFieldGoalMissed { get; set; }
        public Nullable<int> FreeThrowMade { get; set; }
        public Nullable<int> FreeThrowMissed { get; set; }
        public Nullable<int> Rebound { get; set; }
        public Nullable<int> OFFR { get; set; }
        public Nullable<int> DFFR { get; set; }
        public Nullable<int> Steal { get; set; }
        public Nullable<int> Block { get; set; }
        public Nullable<int> Turnover { get; set; }
        public Nullable<int> Foul { get; set; }
    }
}
