//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace УПпрактика
{
    using System;
    using System.Collections.Generic;
    
    public partial class Team
    {
        public int TeamID { get; set; }
        public string TeamName { get; set; }
        public Nullable<byte> DivisionId { get; set; }
        public string Abbr { get; set; }
        public string Coach { get; set; }
        public string Stadium { get; set; }
        public string Logo { get; set; }
    
        public virtual Division Division { get; set; }
    }
}
